/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROLLER.AnimaisController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.etec
 */
public class J_Animal extends javax.swing.JFrame {

    /**
     * Creates new form J_Mamiferos
     */
    public J_Animal() {
        initComponents();
        
        
        jComboBox3.addItem("Mata Atlântica");
        jComboBox3.addItem("Cerrado");
        jComboBox3.addItem("Caatinga");
        jComboBox3.addItem("Pampas");
        jComboBox3.addItem("Savana");
        jComboBox3.addItem("Deserto");
        jComboBox3.addItem("Tundra");
        jComboBox3.addItem("Marinho");
        jComboBox3.addItem("Agua Doce");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        classe = new javax.swing.JLabel();
        textClasse = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textCientifico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textPopular = new javax.swing.JTextField();
        jTextPeso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextIdade = new javax.swing.JTextField();
        jRadioButtonFemea = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonMacho = new javax.swing.JRadioButton();
        Cadastrar1 = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAnimal = new javax.swing.JMenu();
        jMenuHabitat = new javax.swing.JMenu();
        jMenuTratame = new javax.swing.JMenu();
        jMenuveteri = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        LMenuAnimal1 = new javax.swing.JMenu();
        LMenuHabitat1 = new javax.swing.JMenu();
        LMenuTratame1 = new javax.swing.JMenu();
        LMenuveteri1 = new javax.swing.JMenu();

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Base 02", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Animais");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        classe.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        classe.setForeground(new java.awt.Color(255, 255, 255));
        classe.setText("Classe");
        getContentPane().add(classe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        textClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClasseActionPerformed(evt);
            }
        });
        getContentPane().add(textClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 260, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome Cientifico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        getContentPane().add(textCientifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 260, -1));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome Popular");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        getContentPane().add(textPopular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, -1));
        getContentPane().add(jTextPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 260, -1));

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Peso");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Idade");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));
        getContentPane().add(jTextIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 260, -1));

        jRadioButtonFemea.setBackground(new java.awt.Color(153, 153, 153));
        jRadioButtonFemea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonFemea.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFemea.setText("Fêmea");
        jRadioButtonFemea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemeaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFemea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Genêro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 110, -1));

        jRadioButtonMacho.setBackground(new java.awt.Color(153, 153, 153));
        jRadioButtonMacho.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButtonMacho.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMacho.setText("Macho");
        jRadioButtonMacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMachoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonMacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        Cadastrar1.setBackground(new java.awt.Color(204, 204, 204));
        Cadastrar1.setText("Cadastrar");
        Cadastrar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 73, 23));

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setText("Menu");
        menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 73, 23));

        jLabel11.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Habitat");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Genêro");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 110, -1));

        jComboBox3.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox3.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 120, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/animal.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 520));

        jMenu1.setText("Cadastrar");

        jMenuAnimal.setText("Animal");
        jMenuAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAnimalMouseClicked(evt);
            }
        });
        jMenu1.add(jMenuAnimal);

        jMenuHabitat.setText("Habitat");
        jMenuHabitat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHabitatMouseClicked(evt);
            }
        });
        jMenu1.add(jMenuHabitat);

        jMenuTratame.setText("Tratamento");
        jMenuTratame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTratameMouseClicked(evt);
            }
        });
        jMenu1.add(jMenuTratame);

        jMenuveteri.setText("Veterinario");
        jMenuveteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuveteriMouseClicked(evt);
            }
        });
        jMenu1.add(jMenuveteri);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar");

        LMenuAnimal1.setText("Animal");
        LMenuAnimal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMenuAnimal1MouseClicked(evt);
            }
        });
        jMenu2.add(LMenuAnimal1);

        LMenuHabitat1.setText("Habitat");
        LMenuHabitat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMenuHabitat1MouseClicked(evt);
            }
        });
        jMenu2.add(LMenuHabitat1);

        LMenuTratame1.setText("Tratamento");
        LMenuTratame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMenuTratame1MouseClicked(evt);
            }
        });
        jMenu2.add(LMenuTratame1);

        LMenuveteri1.setText("Veterinario");
        LMenuveteri1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMenuveteri1MouseClicked(evt);
            }
        });
        jMenu2.add(LMenuveteri1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMachoActionPerformed
        // TODO add your handling code here:
        
         if(jRadioButtonMacho.isSelected()){
          jRadioButtonMacho.setSelected(true);
          jRadioButtonFemea.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonMachoActionPerformed

    private void textClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textClasseActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        dispose();
        new J_MenuInicial().setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void Cadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar1ActionPerformed
        // TODO add your handling code here:
        char genero;
        CONTROLLER.AnimaisController ani = new AnimaisController();
        if(jRadioButtonFemea.isSelected()){
             genero = 'F';
            
        }else{
                genero = 'M';
             }  
        if ((textClasse.getText().isEmpty() || textCientifico.getText().isEmpty()
                || textPopular.getText().isEmpty() || jTextPeso.getText().isEmpty()||jTextIdade.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os dados não podem retornar vazio");
        } else {

            try {
                ani.salvar(textClasse.getText(), textCientifico.getText(),
                        textPopular.getText(),
                        Float.parseFloat(jTextPeso.getText()),
                        Integer.parseInt(jTextIdade.getText()),    
                        jComboBox3.getSelectedItem().toString());

            } catch (SQLException ex) {
                Logger.getLogger(J_Animal.class.getName()).log(Level.SEVERE, null, ex);
               // erro de tipo de dado recebido(variavel) 
            } catch (ParseException ex) {
                Logger.getLogger(J_Animal.class.getName()).log(Level.SEVERE, null, ex);
            }

            JOptionPane.showMessageDialog(null, "Dados inseridos com sucesso");
        }
        
    }//GEN-LAST:event_Cadastrar1ActionPerformed

    private void jMenuAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAnimalMouseClicked
        dispose();
        new J_Animal().setVisible(true);
    }//GEN-LAST:event_jMenuAnimalMouseClicked

    private void jMenuHabitatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHabitatMouseClicked
        dispose();
        new J_Habitat().setVisible(true);
    }//GEN-LAST:event_jMenuHabitatMouseClicked

    private void jMenuTratameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTratameMouseClicked
        dispose();
        new J_Tratamentos().setVisible(true);
    }//GEN-LAST:event_jMenuTratameMouseClicked

    private void jMenuveteriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuveteriMouseClicked
        dispose();
        new J_Veterinarios().setVisible(true);
    }//GEN-LAST:event_jMenuveteriMouseClicked

    private void LMenuAnimal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMenuAnimal1MouseClicked
        dispose();
        new L_Animal().setVisible(true);
    }//GEN-LAST:event_LMenuAnimal1MouseClicked

    private void LMenuHabitat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMenuHabitat1MouseClicked
        dispose();
        new L_Habitat().setVisible(true);
    }//GEN-LAST:event_LMenuHabitat1MouseClicked

    private void LMenuTratame1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMenuTratame1MouseClicked
        dispose();
        new L_Tratamentos().setVisible(true);
    }//GEN-LAST:event_LMenuTratame1MouseClicked

    private void LMenuveteri1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMenuveteri1MouseClicked
        dispose();
        new L_Veterinarios().setVisible(true);
    }//GEN-LAST:event_LMenuveteri1MouseClicked

    private void jRadioButtonFemeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemeaActionPerformed
        // TODO add your handling code here:
        
          if(jRadioButtonFemea.isSelected()){
          jRadioButtonFemea.setSelected(true);
          jRadioButtonMacho.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonFemeaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(J_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(J_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(J_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(J_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J_Animal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar1;
    private javax.swing.JMenu LMenuAnimal1;
    private javax.swing.JMenu LMenuHabitat1;
    private javax.swing.JMenu LMenuTratame1;
    private javax.swing.JMenu LMenuveteri1;
    private javax.swing.JLabel classe;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAnimal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHabitat;
    private javax.swing.JMenu jMenuTratame;
    private javax.swing.JMenu jMenuveteri;
    private javax.swing.JRadioButton jRadioButtonFemea;
    private javax.swing.JRadioButton jRadioButtonMacho;
    private javax.swing.JTextField jTextIdade;
    private javax.swing.JTextField jTextPeso;
    private javax.swing.JButton menu;
    private javax.swing.JTextField textCientifico;
    private javax.swing.JTextField textClasse;
    private javax.swing.JTextField textPopular;
    // End of variables declaration//GEN-END:variables
}
