/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author lalam
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaDiretor = new javax.swing.JLabel();
        telaGenero = new javax.swing.JLabel();
        telaFilmes = new javax.swing.JLabel();
        telaAtor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        saida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telaDiretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/diretor.png"))); // NOI18N
        telaDiretor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        telaDiretor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaDiretorMouseClicked(evt);
            }
        });
        getContentPane().add(telaDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 100, 100));

        telaGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/genero.png"))); // NOI18N
        telaGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        telaGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaGeneroMouseClicked(evt);
            }
        });
        getContentPane().add(telaGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 100, 100));

        telaFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/filme.png"))); // NOI18N
        telaFilmes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        telaFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaFilmesMouseClicked(evt);
            }
        });
        getContentPane().add(telaFilmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 100, 100));

        telaAtor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ator.png"))); // NOI18N
        telaAtor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        telaAtor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaAtorMouseClicked(evt);
            }
        });
        getContentPane().add(telaAtor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 100));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setText("       Ator");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 20));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel7.setText("    Diretor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 100, 20));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel8.setText("     Filmes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 100, 20));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setText("    Genêro");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 100, 20));

        saida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/saida.png"))); // NOI18N
        saida.setText("Saída");
        saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saidaMouseClicked(evt);
            }
        });
        getContentPane().add(saida, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        jMenu2.setText("Login");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_saidaMouseClicked

    private void telaAtorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaAtorMouseClicked
        dispose();
        new Ator().setVisible(true);
    }//GEN-LAST:event_telaAtorMouseClicked

    private void telaDiretorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaDiretorMouseClicked
        dispose();
        new Diretor().setVisible(true);
    }//GEN-LAST:event_telaDiretorMouseClicked

    private void telaFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaFilmesMouseClicked
        dispose();
        new Filme().setVisible(true);
    }//GEN-LAST:event_telaFilmesMouseClicked

    private void telaGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telaGeneroMouseClicked
        dispose();
        new Genero().setVisible(true);
    }//GEN-LAST:event_telaGeneroMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
           dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel saida;
    private javax.swing.JLabel telaAtor;
    private javax.swing.JLabel telaDiretor;
    private javax.swing.JLabel telaFilmes;
    private javax.swing.JLabel telaGenero;
    // End of variables declaration//GEN-END:variables
}
